// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delta struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ContinentDelta struct {
	Token                *Token            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Targets              map[string]*Delta `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContinentDelta) Reset()         { *m = ContinentDelta{} }
func (m *ContinentDelta) String() string { return proto.CompactTextString(m) }
func (*ContinentDelta) ProtoMessage()    {}
func (*ContinentDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *ContinentDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinentDelta.Unmarshal(m, b)
}
func (m *ContinentDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinentDelta.Marshal(b, m, deterministic)
}
func (m *ContinentDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinentDelta.Merge(m, src)
}
func (m *ContinentDelta) XXX_Size() int {
	return xxx_messageInfo_ContinentDelta.Size(m)
}
func (m *ContinentDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinentDelta.DiscardUnknown(m)
}

var xxx_messageInfo_ContinentDelta proto.InternalMessageInfo

func (m *ContinentDelta) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ContinentDelta) GetTargets() map[string]*Delta {
	if m != nil {
		return m.Targets
	}
	return nil
}

type CountryDelta struct {
	Token                *Token            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Targets              map[string]*Delta `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CountryDelta) Reset()         { *m = CountryDelta{} }
func (m *CountryDelta) String() string { return proto.CompactTextString(m) }
func (*CountryDelta) ProtoMessage()    {}
func (*CountryDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *CountryDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountryDelta.Unmarshal(m, b)
}
func (m *CountryDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountryDelta.Marshal(b, m, deterministic)
}
func (m *CountryDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryDelta.Merge(m, src)
}
func (m *CountryDelta) XXX_Size() int {
	return xxx_messageInfo_CountryDelta.Size(m)
}
func (m *CountryDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryDelta.DiscardUnknown(m)
}

var xxx_messageInfo_CountryDelta proto.InternalMessageInfo

func (m *CountryDelta) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CountryDelta) GetTargets() map[string]*Delta {
	if m != nil {
		return m.Targets
	}
	return nil
}

type CityDelta struct {
	Token                *Token            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Targets              map[string]*Delta `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CityDelta) Reset()         { *m = CityDelta{} }
func (m *CityDelta) String() string { return proto.CompactTextString(m) }
func (*CityDelta) ProtoMessage()    {}
func (*CityDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *CityDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityDelta.Unmarshal(m, b)
}
func (m *CityDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityDelta.Marshal(b, m, deterministic)
}
func (m *CityDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityDelta.Merge(m, src)
}
func (m *CityDelta) XXX_Size() int {
	return xxx_messageInfo_CityDelta.Size(m)
}
func (m *CityDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_CityDelta.DiscardUnknown(m)
}

var xxx_messageInfo_CityDelta proto.InternalMessageInfo

func (m *CityDelta) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CityDelta) GetTargets() map[string]*Delta {
	if m != nil {
		return m.Targets
	}
	return nil
}

type City struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Cities struct {
	Values               []*City  `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cities) Reset()         { *m = Cities{} }
func (m *Cities) String() string { return proto.CompactTextString(m) }
func (*Cities) ProtoMessage()    {}
func (*Cities) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *Cities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cities.Unmarshal(m, b)
}
func (m *Cities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cities.Marshal(b, m, deterministic)
}
func (m *Cities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cities.Merge(m, src)
}
func (m *Cities) XXX_Size() int {
	return xxx_messageInfo_Cities.Size(m)
}
func (m *Cities) XXX_DiscardUnknown() {
	xxx_messageInfo_Cities.DiscardUnknown(m)
}

var xxx_messageInfo_Cities proto.InternalMessageInfo

func (m *Cities) GetValues() []*City {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Delta)(nil), "internal.Delta")
	proto.RegisterType((*ContinentDelta)(nil), "internal.ContinentDelta")
	proto.RegisterMapType((map[string]*Delta)(nil), "internal.ContinentDelta.TargetsEntry")
	proto.RegisterType((*CountryDelta)(nil), "internal.CountryDelta")
	proto.RegisterMapType((map[string]*Delta)(nil), "internal.CountryDelta.TargetsEntry")
	proto.RegisterType((*CityDelta)(nil), "internal.CityDelta")
	proto.RegisterMapType((map[string]*Delta)(nil), "internal.CityDelta.TargetsEntry")
	proto.RegisterType((*City)(nil), "internal.City")
	proto.RegisterType((*Cities)(nil), "internal.Cities")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0xab, 0xda, 0x40,
	0x14, 0xc5, 0x19, 0x35, 0xb1, 0x5e, 0xff, 0x54, 0xa6, 0x45, 0x42, 0x4a, 0x41, 0x52, 0x2c, 0xae,
	0x62, 0x49, 0x37, 0xad, 0x50, 0x84, 0xa6, 0xae, 0xba, 0x0b, 0x42, 0xd7, 0xb1, 0xdc, 0x17, 0x07,
	0xe3, 0x8c, 0x64, 0x26, 0x0f, 0xfc, 0x6c, 0x6f, 0xf5, 0x16, 0xef, 0x63, 0x3d, 0x78, 0x64, 0x26,
	0xc1, 0x3f, 0x98, 0x85, 0x1b, 0x77, 0x99, 0x99, 0x73, 0x7f, 0xf7, 0x9c, 0xcc, 0x5c, 0xe8, 0x49,
	0x8c, 0xb3, 0xff, 0x1b, 0x7f, 0x9f, 0x09, 0x25, 0xe8, 0x3b, 0xc6, 0x15, 0x66, 0x3c, 0x4e, 0xdd,
	0x4f, 0x89, 0x10, 0x49, 0x8a, 0x33, 0xbd, 0xbf, 0xce, 0x1f, 0x66, 0xb8, 0xdb, 0xab, 0x83, 0x91,
	0xb9, 0x7d, 0x89, 0x52, 0x32, 0xc1, 0xcd, 0xd2, 0xfb, 0x0c, 0xd6, 0x1f, 0x4c, 0x55, 0x4c, 0x3f,
	0x82, 0xf5, 0x18, 0xa7, 0x39, 0x3a, 0x64, 0x4c, 0xa6, 0x56, 0x64, 0x16, 0xde, 0x0b, 0x81, 0x41,
	0x28, 0xb8, 0x62, 0x1c, 0xb9, 0x32, 0xc2, 0x09, 0x58, 0x4a, 0x6c, 0x91, 0x6b, 0x61, 0x37, 0x78,
	0xef, 0x57, 0x7d, 0xfd, 0x55, 0xb1, 0x1d, 0x99, 0x53, 0xba, 0x80, 0xb6, 0x8a, 0xb3, 0x04, 0x95,
	0x74, 0x1a, 0xe3, 0xe6, 0xb4, 0x1b, 0x4c, 0x8e, 0xc2, 0x73, 0xa2, 0xbf, 0x32, 0xba, 0x25, 0x57,
	0xd9, 0x21, 0xaa, 0xaa, 0xdc, 0xbf, 0xd0, 0x3b, 0x3d, 0xa0, 0x43, 0x68, 0x6e, 0xf1, 0xa0, 0xbb,
	0x76, 0xa2, 0xe2, 0xb3, 0x70, 0x62, 0x2c, 0x37, 0x2e, 0x9d, 0x68, 0x6e, 0x99, 0x61, 0xde, 0xf8,
	0x41, 0xbc, 0x67, 0x02, 0xbd, 0x50, 0xe4, 0x05, 0xe8, 0xa6, 0x14, 0xbf, 0x2e, 0x53, 0x7c, 0x39,
	0x4d, 0x71, 0xe4, 0xdd, 0x23, 0xc3, 0x13, 0x81, 0x4e, 0xc8, 0xd4, 0x6d, 0x01, 0xe6, 0x97, 0x01,
	0xc6, 0x27, 0x01, 0x2a, 0xd8, 0x3d, 0xdc, 0xbb, 0xd0, 0x2a, 0xfa, 0x51, 0x0a, 0x2d, 0x1e, 0xef,
	0xb0, 0xa4, 0xe8, 0x6f, 0xef, 0x1b, 0xd8, 0x21, 0x53, 0x0c, 0x25, 0xfd, 0x0a, 0xb6, 0x2e, 0x91,
	0x0e, 0xd1, 0x6e, 0x07, 0xe7, 0x6e, 0xa3, 0xf2, 0x34, 0x78, 0x25, 0xd0, 0xfe, 0x87, 0x2c, 0xd9,
	0x28, 0x49, 0x7f, 0xc3, 0x20, 0xdc, 0xc4, 0x3c, 0xc1, 0xf2, 0x59, 0x29, 0xea, 0xd4, 0x3d, 0x35,
	0x77, 0xe4, 0x9b, 0xd9, 0xf0, 0xab, 0xd9, 0xf0, 0x97, 0xc5, 0x6c, 0xd0, 0x05, 0xf4, 0x2b, 0x86,
	0xbe, 0x54, 0x3a, 0xba, 0x7e, 0xcf, 0xb5, 0x80, 0x9f, 0x00, 0x25, 0xa0, 0x08, 0xf9, 0xe1, 0xca,
	0x4f, 0xae, 0x2d, 0x0d, 0xc0, 0x8e, 0x50, 0xe6, 0xa9, 0xa2, 0x35, 0x0a, 0x77, 0x78, 0x86, 0x63,
	0x28, 0xd7, 0xb6, 0x56, 0x7c, 0x7f, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x00, 0x51, 0x92, 0x03,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WeightsClient is the client API for Weights service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeightsClient interface {
	ChangeContinet(ctx context.Context, in *ContinentDelta, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeCountry(ctx context.Context, in *CountryDelta, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeCity(ctx context.Context, in *CityDelta, opts ...grpc.CallOption) (*empty.Empty, error)
	Result(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Cities, error)
}

type weightsClient struct {
	cc *grpc.ClientConn
}

func NewWeightsClient(cc *grpc.ClientConn) WeightsClient {
	return &weightsClient{cc}
}

func (c *weightsClient) ChangeContinet(ctx context.Context, in *ContinentDelta, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/internal.Weights/ChangeContinet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightsClient) ChangeCountry(ctx context.Context, in *CountryDelta, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/internal.Weights/ChangeCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightsClient) ChangeCity(ctx context.Context, in *CityDelta, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/internal.Weights/ChangeCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightsClient) Result(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Cities, error) {
	out := new(Cities)
	err := c.cc.Invoke(ctx, "/internal.Weights/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightsServer is the server API for Weights service.
type WeightsServer interface {
	ChangeContinet(context.Context, *ContinentDelta) (*empty.Empty, error)
	ChangeCountry(context.Context, *CountryDelta) (*empty.Empty, error)
	ChangeCity(context.Context, *CityDelta) (*empty.Empty, error)
	Result(context.Context, *empty.Empty) (*Cities, error)
}

// UnimplementedWeightsServer can be embedded to have forward compatible implementations.
type UnimplementedWeightsServer struct {
}

func (*UnimplementedWeightsServer) ChangeContinet(ctx context.Context, req *ContinentDelta) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeContinet not implemented")
}
func (*UnimplementedWeightsServer) ChangeCountry(ctx context.Context, req *CountryDelta) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeCountry not implemented")
}
func (*UnimplementedWeightsServer) ChangeCity(ctx context.Context, req *CityDelta) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeCity not implemented")
}
func (*UnimplementedWeightsServer) Result(ctx context.Context, req *empty.Empty) (*Cities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}

func RegisterWeightsServer(s *grpc.Server, srv WeightsServer) {
	s.RegisterService(&_Weights_serviceDesc, srv)
}

func _Weights_ChangeContinet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinentDelta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServer).ChangeContinet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Weights/ChangeContinet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServer).ChangeContinet(ctx, req.(*ContinentDelta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weights_ChangeCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryDelta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServer).ChangeCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Weights/ChangeCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServer).ChangeCountry(ctx, req.(*CountryDelta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weights_ChangeCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityDelta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServer).ChangeCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Weights/ChangeCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServer).ChangeCity(ctx, req.(*CityDelta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weights_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Weights/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServer).Result(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Weights_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Weights",
	HandlerType: (*WeightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeContinet",
			Handler:    _Weights_ChangeContinet_Handler,
		},
		{
			MethodName: "ChangeCountry",
			Handler:    _Weights_ChangeCountry_Handler,
		},
		{
			MethodName: "ChangeCity",
			Handler:    _Weights_ChangeCity_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _Weights_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
